repository:
  security_and_analysis:
    advanced_security:
      status: enabled
    secret_scanning:
      status: enabled

  has_issues: true
  has_discussions: true
  has_projects: true
  has_wiki: true
  has_downloads: true
  default_branch: main

  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  allow_auto_merge: false
  delete_branch_on_merge: true

  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

labels:
  - name: "Priority: Critical"
    color: "000000"
  - name: "Priority: High"
    color: "F9D0C4"
  - name: "Priority: Medium"
    color: "FEF2C0"
  - name: "Priority: Low"
    color: "D4C5F9"
  - name: "State: Help Wanted"
    color: "0E8A16"
  - name: "State: Work in Progress"
    color: "5319E7"
  - name: "State: Blocked"
    color: "000000"
  - name: "State: Postponed"
    color: "C5DEF5"
  - name: "Type: Enhancement"
    color: "1D76DB"
  - name: "Type: Bug"
    color: "B60205"
  - name: "Type: Infrastructure"
    color: "FBCA04"
  - name: "Type: Dependencies"
    color: "D4C5F9"
  - name: "Meta: Question"
    color: "BFDADC"
  - name: "Meta: Conversation"
    color: "27828C"
  - name: "Meta: Duplicate"
    color: "BFDADC"
  - name: "Meta: Abandoned / No Fix"
    color: "808080"

branches:
  - name: main
    protection:
      allow_deletions: false
